name: localization_hrms_example
description: Example app demonstrating localization_hrms package usage.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization_hrms:
    path: ../          # references the local package
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
